# .github/workflows/update-reappro.yml
name: Daily update – Native Spirit reappro CSV

on:
  schedule:
    - cron: '0 02 * * *'   # tous les jours à 02:00 UTC
  workflow_dispatch:        # lancement manuel possible

jobs:
  update-reappro:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout avec historique complet (utile si tu veux comparer proprement)
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      # 2) Alignement sur la branche distante
      - name: Reset local → remote (main)
        run: |
          git fetch origin main
          git reset --hard origin/main

      # 3) Télécharger le CSV de réappro Native Spirit
      - name: Download NATIVE_SPIRIT_REAPPROWEB_NS.csv
        run: |
          mkdir -p public
          curl -fSL "https://files.nativespirit-ns.com/documents/NATIVE_SPIRIT_REAPPROWEB_NS.csv" \
            -o public/NATIVE_SPIRIT_REAPPROWEB_NS.csv

      # 4) Sanity check (fichier non vide)
      - name: Sanity check
        run: |
          test -s public/NATIVE_SPIRIT_REAPPROWEB_NS.csv || (echo "CSV vide ou introuvable" && exit 1)

      # 5) Commit & push uniquement si le CSV a changé
      - name: Commit & push if changed
        run: |
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          git add public/NATIVE_SPIRIT_REAPPROWEB_NS.csv

          if git diff --cached --quiet; then
            echo "Aucun changement détecté – pas de commit/push."
            exit 0
          fi

          git commit -m "chore(NS): daily reappro CSV update"
          git push origin main

